apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-admin
  namespace: workshop-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: workshop-k8s
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: workshop-k8s
subjects:
- kind: ServiceAccount
  name: workshop-admin
  namespace: workshop-k8s
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
