apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mlflow"
  MLFLOW_HOST: "mlflow-service"
  MLFLOW_PORT: "5000"
  CHROMA_HOST: "chromadb-service"
  CHROMA_PORT: "8000"
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
