apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  RABBITMQ_USER: admin
  RABBITMQ_PASS: admin123
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: mlflow123
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin123
